version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: hexagonal-postgres-v2
    environment:
      POSTGRES_DB: hexagonal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: hexagonal-redis-v2
    ports:
      - "6379:6379"

  hexagonal-template-v2:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hexagonal-template-v2
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hexagonal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  postgres-data:

